In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot  as plt
import seaborn as sns

In [3]:
bureau=pd.read_csv('bureau_data.csv')
customers=pd.read_csv('customers.csv')
loans=pd.read_csv('loans.csv')

In [4]:
bureau

,cust_id,number_of_open_accounts,number_of_closed_accounts,total_loan_months,delinquent_months,total_dpd,enquiry_count,credit_utilization_ratio
0,C00001,1,1,42,0,0,3,7
1,C00002,3,1,96,12,60,5,4
2,C00003,2,1,82,24,147,6,58
3,C00004,3,0,115,15,87,5,26
4,C00005,4,2,120,0,0,5,10
...,...,...,...,...,...,...,...,...
49995,C49996,4,2,165,1,6,8,24
49996,C49997,4,0,161,0,0,4,91
49997,C49998,4,1,42,0,0,7,38
49998,C49999,1,2,42,9,47,4,17
49999,C50000,2,0,65,13,66,7,28

In [5]:
bureau.shape

(50000, 8)

In [6]:
customers.shape

(50000, 12)

In [7]:
loans.shape

(50000, 15)

In [8]:
bureau.describe()

,number_of_open_accounts,number_of_closed_accounts,total_loan_months,delinquent_months,total_dpd,enquiry_count,credit_utilization_ratio
count,50000.000000,50000.00000,50000.000000,50000.00000,50000.000000,50000.000000,50000.00000
mean,2.500140,1.00106,76.127140,4.87890,26.858000,5.009340,43.36142
std,1.118725,0.81412,43.762469,5.85032,32.832832,2.029122,29.35598
min,1.000000,0.00000,1.000000,0.00000,0.000000,1.000000,0.00000
25%,1.000000,0.00000,42.000000,0.00000,0.000000,4.000000,18.00000
50%,3.000000,1.00000,71.000000,3.00000,14.000000,5.000000,39.00000
75%,4.000000,2.00000,107.000000,9.00000,46.000000,6.000000,67.00000
max,4.000000,2.00000,223.000000,24.00000,171.000000,9.000000,99.00000

In [9]:
customers.describe()

,age,income,number_of_dependants,years_at_current_address,zipcode
count,50000.000000,5.000000e+04,50000.000000,50000.000000,50000.000000
mean,39.550980,2.640898e+06,1.939540,16.018440,419090.860000
std,9.847752,2.629441e+06,1.535517,8.926489,168982.674047
min,18.000000,0.000000e+00,0.000000,1.000000,110001.000000
25%,33.000000,8.030000e+05,0.000000,8.000000,302001.000000
50%,40.000000,1.892000e+06,2.000000,16.000000,400001.000000
75%,46.000000,3.332250e+06,3.000000,24.000000,560001.000000
max,70.000000,1.199900e+07,5.000000,31.000000,700001.000000

In [10]:
loans.describe()

,sanction_amount,loan_amount,processing_fee,gst,net_disbursement,loan_tenure_months,principal_outstanding,bank_balance_at_application
count,5.000000e+04,5.000000e+04,5.000000e+04,5.000000e+04,5.000000e+04,50000.000000,5.000000e+04,5.000000e+04
mean,4.704828e+06,3.999679e+06,8.049471e+04,7.199422e+05,3.199743e+06,25.940520,1.337636e+06,9.891264e+05
std,6.267276e+06,5.376552e+06,1.173123e+05,9.677794e+05,4.301242e+06,12.433163,1.214714e+06,1.046072e+06
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.000000,-1.000000e+00,0.000000e+00
25%,1.147000e+06,9.670000e+05,1.934000e+04,1.740600e+05,7.736000e+05,16.000000,4.247990e+05,2.870075e+05
50%,2.656000e+06,2.240000e+06,4.480000e+04,4.032000e+05,1.792000e+06,24.000000,1.002309e+06,6.685250e+05
75%,5.172250e+06,4.611000e+06,9.224000e+04,8.299800e+05,3.688800e+06,35.000000,1.790751e+06,1.238667e+06
max,5.217500e+07,4.781900e+07,5.698030e+06,8.607420e+06,3.825520e+07,59.000000,5.000000e+06,7.846643e+06

In [11]:
bureau.isnull().sum()

cust_id                      0
number_of_open_accounts      0
number_of_closed_accounts    0
total_loan_months            0
delinquent_months            0
total_dpd                    0
enquiry_count                0
credit_utilization_ratio     0
dtype: int64

In [14]:
customers.isnull().sum()

cust_id                      0
age                          0
gender                       0
marital_status               0
employment_status            0
income                       0
number_of_dependants         0
residence_type              62
years_at_current_address     0
city                         0
state                        0
zipcode                      0
dtype: int64

### customers-> residence type contains some null value

In [16]:
loans.isnull().sum()

loan_id                        0
cust_id                        0
loan_purpose                   0
loan_type                      0
sanction_amount                0
loan_amount                    0
processing_fee                 0
gst                            0
net_disbursement               0
loan_tenure_months             0
principal_outstanding          0
bank_balance_at_application    0
disbursal_date                 0
installment_start_dt           0
default                        0
dtype: int64